### ISSUE TITLE
ERROR: fs: re-evaluating native module sources is not supported. 

### ISSUE THREAD

**Issue by lukeorland** [opensprints/opensprints-electron#1]
```
$ gulp
(node:34867) fs: re-evaluating native module sources is not supported. If you are using the graceful-fs module, please update it to a more recent version.
module.js:442
    throw err;
    ^

Error: Cannot find module 'gulp-sass'
    at Function.Module._resolveFilename (module.js:440:15)
    at Function.Module._load (module.js:388:25)
    at Module.require (module.js:468:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/Users/orluke/workspace/opensprints-electron/gulpfile.js:2:10)
    at Module._compile (module.js:541:32)
    at Object.Module._extensions..js (module.js:550:10)
    at Module.load (module.js:458:32)
    at tryModuleLoad (module.js:417:12)
    at Function.Module._load (module.js:409:3)
```

I updated `graceful-fs` to the latest version, 4.1.5, but that did not fix it.

I also tried this: https://github.com/sequelize/cli/issues/291#issuecomment-236796119
without success.

*System:* OS X 10.11.6

**Comment by lukeorland** [comment]
I also tried installing the `gulp-sass` npm package (locally and globally). Still got the same error. I'll try updating the electron binaries next.

**Comment by lukeorland** [comment]
I tried installing the `electron-prebuilt` npm package but still got the same error.

**Comment by nickstew** [comment]
Try using node v6.3.1 and before you run `npm install` make sure to delete your `node_modules` directory.  `node_modules` has a tendency to get into a weird state with libraries that have to be compiled for specific environments.  Let me know if that helps.

**Comment by nickstew** [comment]
Also, I forgot to update the readme when I converted the application to use React/Redux.  Sorry Luke!  I just updated the README to include the proper steps.  `gulp` isn't required anymore.

**Comment by nickstew** [comment]
@lukeorland, I just copied a bunch of elements from the boilerplate readme that I started the rewrite from.

**Comment by lukeorland** [comment]
cool. I followed the instructions in the new README. works fine:

![image](https://cloud.githubusercontent.com/assets/11611/17390051/6dbdcab4-59d7-11e6-8ae8-7b2a18fe4aaf.png)

**Comment by lukeorland** [comment]
BTW, feel free to put some issues up for me to work on. I could also focus on creating an npm package that handles the Arduino hardware, that this project could import.

**Comment by nickstew** [comment]
The one thing I'm really concerned about is the interface with the hardware.  If you could port the functionality in the previous Arduino code to Johnny-Five that would be amazing.  We'll need it as soon as I build a way to start a race.

Hopefully by the end of this weekend I'll have barebones functionality of:
- [x] Creating a `Racer`
- [ ] Creating a `Race`
- [ ] Running a `Race` (hardware test)
