### ISSUE TITLE
Default Settings - Change Backgrounds

### ISSUE THREAD

**Issue by nickstew** [opensprints/opensprints-electron#11]
![161851615](https://cloud.githubusercontent.com/assets/1165359/21783820/1d6436e0-d676-11e6-87b6-3c1539a99e25.png)

Changing the backgrounds is instrumental to a customer running their own branded event.

Needs to:

- [x] Download corresponding templates in attached zip file
- [x] Ability to "upload" or save in the install directory or directory the App uses to pull backgrounds
- [x] Background dependent on Settings

Last item in this list might need it's own issue due to scope.

[Background Templates.zip](https://github.com/opensprints/opensprints-electron/files/694700/Background.Templates.zip)

**Comment by jonfen** [comment]
@nickstew what is the question?

**Comment by nickstew** [comment]
I guess I'm just having trouble figuring out how to abstract the background from the rest of the app.  Right now it's just static css set on the top level `div` or `body` tag.  It may not really be a question, I just need some input/collaboration on ideas.
