### ISSUE TITLE
Add Interface for Setting up and Running a Race

### ISSUE THREAD

**Issue by nickstew** [opensprints/opensprints-electron#2]
This interface should have similar functionality to [arduino racemonitor](https://github.com/opensprints/opensprints-comm/blob/master/arduino/racemonitor/racemonitor.pde).

**Comment by lukeorland** [comment]
Here is a node module for this purpose: https://github.com/opensprints/opensprints-hw-js

I'll work on integrating it into this repo.

Uploading the module to the npm registry will probably be useful.

**Comment by nickstew** [comment]
@lukeorland will this run as a separate process on the machine?  I haven't done much of that with node, but it would be cool to see in action.
