### ISSUE TITLE
Uncaught Error: module version mismatch. Expected 50, got 48. bindings.js

### ISSUE THREAD

**Issue by nickstew** [opensprints/opensprints-electron#5]
# Issue

<img width="713" alt="screen shot 2016-09-27 at 8 07 45 am" src="https://cloud.githubusercontent.com/assets/1165359/18877557/dac79fda-848a-11e6-8773-c5ab67317260.png">

## Investigation

This issue lies somewhere between `electron` and `serialport`.   Thanks to [#1204](https://github.com/rwaldron/johnny-five/issues/1204) and [this comment](https://github.com/rwaldron/johnny-five/issues/1204#issuecomment-245332246), I was able to come up with a solution for this problem.  I hope this leads you in the right direction. 

### Install `node-gyp` Globally

I did this to make it easier to reference later when we rebuild `serialport` with it.

```bash
  npm install -g node-gyp
```

### Change Directory to where `serialport` is in your project

`node-gyp` is going to use the current directory for which module to rebuild.

```bash
  cd `npm ls serialport --parseable`
```

### Rebuild `serialport`

This is mostly taken from that issue comment linked above.  

I assume that we need to reference `~/.electron-gyp` so that it uses the `electron` version as the targeted version instead of using an `electron` version number to target a specific version of `node`.

I added the dynamic target so that as `electron` gets updated you won't have to change this line.

```bash
  HOME=~/.electron-gyp node-gyp rebuild --target=`npm view electron version` --arch=x64 --dist http://atom.io/download/atom-shell
```

# Done!

After that you should be good to navigate back to the root of your project and run it.

## Obligatory Version Table and Disclaimer

| OS | node | npm | electron | johnny-five | serialport |
| :---: | :---: | :---: | :---: | :---: | :---: |
| OSX 10.11.6 | 6.3.1 | 2.11.3 | 1.4.1 | 0.10.1 | 4.0.1 |

**Disclaimer: I have only verified that it works on my machine and have not tried Windows or Linux operating systems.**

**Comment by lukeorland** [comment]
I followed these instructions and was successful, in that I didn't get the "Module version mismatch" exception. However, I couldn't figure out how to use the UI to get a race running.

**Comment by nickstew** [comment]
Hey Luke, go to the race screen and it should try to connect to the
hardware.  Sorry, I'm about to go into cataract Canyon. Talk to you on
Sunday.

**Comment by taktran** [comment]
I had this issue with [xpc-connection](https://github.com/sandeepmistry/node-xpc-connection) for bluetooth, and worked amazingly! Thanks!

**Comment by taktran** [comment]
Actually using [electron-rebuild](https://github.com/electron/electron-rebuild) seems to fix the problem
