### ISSUE TITLE
Indicator Needles on Race Screen needs proper styling

### ISSUE THREAD

**Issue by nickstew** [opensprints/opensprints-electron#9]

**Comment by nickstew** [comment]
![144309033](https://cloud.githubusercontent.com/assets/1165359/21782843/256f7ac4-d672-11e6-872f-e1c9f57f4665.jpg)

Should look like the mockups above.  Or something similar.

**Comment by jonfen** [comment]
@nickstew what is the issue you are currently running into?  Just CSS or something else?

**Comment by nickstew** [comment]
This is one of the few issues.  I am adding more and will try to create a milestone of Version 1 that will have everything left for us to be done.  I am also thinking about a Version 0.9 that won't have the installation or some of the frills as Version 1.  Should I just make a Version 1 milestone, @jonfen?

**Comment by nickstew** [comment]
@jonfen Sorry, I forgot I already had this listed as another issue.

**Comment by nickstew** [comment]
Duplicate of #8
